ist: trusty
sudo: false

language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

jobs:
  include:
    # Run the unit test suite three times in parallel.
    # The first one gets results faster and is the only one required to pass.
    # The second one generates the coverage report.
    # The third one is to keep us informed about possible issues with the
    # upcoming solidity release.
    - stage: tests
      name: "unit tests"
      script: make test
   


on_pull_requests: false