ist: trusty
sudo: false

language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

jobs:
  include:

    - stage: tests
      name: "unit tests"
      script: make test

    - stage: clean
      name: "clean"
      script: make clean
   


on_pull_requests: false
